name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4
        with:
          node-version: 20.9.0
          yarn-version: 4.0.0

      - name: Use Node.js & YARN with Volta
        run: volta install node@20.9.0 yarn@4.0.0   

      - name: Install dependencies
        run: yarn install --silent 2>&1

      - name: Build the app
        run: yarn run build:invoiceViewer

      - name: Copy files from apps/invoiceViewer/dist to current directory
        run: cp -r apps/invoiceViewer/dist/* ./

      - name: Copy files from apps/invoiceViewer/public to current directory
        run: cp -r apps/invoiceViewer/public/* ./ 

      - name: Deploy invoiceViewer to QA
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b qa
          git add ./
          git commit -m "Deploy to qa"
          git push -f origin qa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy invoiceViewer to PROD
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b prod
          git reset --hard
          git cherry-pick qa -Xtheirs --allow-empty
          git cherry-pick --continue --allow-empty
          git push -f origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          