name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4
        with:
          node-version: 20.8.1
          yarn-version: 4.0.0

      - name: Use Node.js & YARN with Volta
        run: volta install    

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn run build:invoiceViewer

      - name: Deploy invoiceViewer to GitHub Pages (PROD)
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b prod
          git add -f apps/invoiceViewer/dist
          git commit -m "Deploy to prod"
          git push -f origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
