name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: yarn

      - name: Build the app
        run: yarn run build:invoiceViewer

      - name: Deploy invoiceViewer to GitHub Pages (PROD)
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b prod
          git add -f apps/invoiceViewer/dist
          git commit -m "Deploy to prod"
          git push -f origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
