name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4
        with:
          node-version: 20.9.0
          yarn-version: 4.0.0

      - name: Use Node.js & YARN with Volta
        run: volta install node@20.9.0 yarn@4.0.0 

      - name: Install dependencies
        run: cd FE/ReactVite && yarn install --silent 2>&1

      - name: Build the app
        run: cd FE/ReactVite && yarn run build:invoiceViewer

      - name: Run unit tests
        run: cd FE/ReactVite && yarn run test:unit
        
      - name: Deploy invoiceViewer to QA
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b ghp-qa-react-vite
          cp ./FE/ReactVite/apps/invoiceViewer/dist . -r
          cp ./FE/ReactVite/apps/invoiceViewer/public . -r
          git add .
          git commit -m "Deploy to qa"
          git push -f origin ghp-qa-react-vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: cd FE/ReactVite && yarn run test:e2e-qa

      - name: Deploy invoiceViewer to PROD
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b ghp-prod-react-vite
          git reset --hard
          git rebase -Xtheirs ghp-qa-react-vite
          git push -f origin ghp-prod-react-vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          