name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Volta
        run: curl https://get.volta.sh | bash -s -- --skip-setup

      - name: Set Volta Environment Variables
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"  

      - name: Setup Node.js and Yarn with Volta
        run: volta install node@20 yarn
        env:
          VOLTA_HOME: /home/runner/.volta

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn run build:invoiceViewer

      - name: Deploy invoiceViewer to GitHub Pages (PROD)
        run: |
          git config --global user.email "asaveiflorin@gmail.com"
          git config --global user.name "Florin Asavei"
          git checkout -b prod
          git add -f apps/invoiceViewer/dist
          git commit -m "Deploy to prod"
          git push -f origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
